# Generated by Django 5.0.2 on 2024-04-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='assignments',
        ),
    ]
