# Generated by Django 5.0.2 on 2024-04-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_employee_assignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='full_name',
            new_name='fullName',
        ),
    ]
