# Generated by Django 5.0.2 on 2024-04-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
