# Generated by Django 5.0.2 on 2024-05-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_surgery_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='is_checkup',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
